package(
    default_visibility = [
        "//bank_ocr:internal",
    ],
)

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

package_group(
    name = "internal",
    packages = [ 
        "//bank_ocr/...",
    ],  
)
